# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Полушин Владимир Владимирович

Группа: 317

In [2]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [5]:
[x for x in range(101) if x % 7 == 0 and x % 5 != 0]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [2]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [2]:
def sort_tokens(s):
    return ",".join(sorted(s.split(",")))
print(sort_tokens('d,c,b,a'))
print(sort_tokens(u"ночь,фонарь,улица"))
print(sort_tokens(u" вмк,это лучший факультет,а мехмат, худший"))

a,b,c,d
ночь,улица,фонарь
 вмк, худший,а мехмат,это лучший факультет


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [3]:
def remove_duplicates(a):
    return sorted(set(a))
print(" ".join(remove_duplicates([u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"])))
print(" ".join(remove_duplicates(["z", "a", "b", "c", "d", "e", "f", "a", "f", "d", "e"])))

аптека ночь улица фонарь
a b c d e f z


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [4]:
map(lambda x: x.lower(), ["abCDefg", "HIjkL"])

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [51]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [5]:
from collections import defaultdict
d = defaultdict(int)
print d
d['abc'] += 1
print d
d['xxx']
print d

defaultdict(<type 'int'>, {})
defaultdict(<type 'int'>, {'abc': 1})
defaultdict(<type 'int'>, {'xxx': 0, 'abc': 1})


In [6]:
from collections import defaultdict
from functools import reduce
def word_counts(texts):
    d = defaultdict(int)
    words = reduce(lambda a, b: a + b, map(lambda text: text.split(" "), texts))
    for word in words:
        d[word] += 1
    for item in d.items():
        print(" ".join(map(unicode, item)))
word_counts([u'ночь улица фонарь аптека', u'аптека улица фонарь'])

аптека 2
улица 2
фонарь 2
ночь 1


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Удалите из него все специальные символы и цифры. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [7]:
from urllib import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [8]:
raw_text[1000:1100]

u'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [20]:
import re
from collections import defaultdict
d = defaultdict(int)
words = re.findall('[A-Za-z]+', raw_text)
for word in words:
    d[word.lower()] += 1
words_with_count = [(item[1], item[0]) for item in d.items()]
print("Top 20")
print(sorted(words_with_count, reverse=True)[:20])
print("Only once 20")
print(sorted(words_with_count)[:20])

Top 20
[(8003, u'the'), (7042, u'and'), (5497, u'to'), (4900, u'he'), (4668, u'a'), (4405, u'i'), (4118, u'you'), (3928, u'of'), (3463, u'it'), (3308, u'that'), (3254, u'in'), (2827, u'was'), (2116, u'his'), (2082, u'at'), (1829, u'her'), (1801, u'but'), (1775, u'not'), (1765, u's'), (1757, u'with'), (1695, u'she')]
Only once 20
[(1, u'abandoning'), (1, u'abasement'), (1, u'abide'), (1, u'abject'), (1, u'abjectly'), (1, u'abjectness'), (1, u'abjure'), (1, u'abnegation'), (1, u'abnormality'), (1, u'abolition'), (1, u'abominably'), (1, u'abortions'), (1, u'abraham'), (1, u'abrupt'), (1, u'abundant'), (1, u'abused'), (1, u'abyss'), (1, u'academy'), (1, u'accelerate'), (1, u'accent')]


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [12]:
vals = np.empty(1000)
for i in range(1000):
    m1 = np.random.normal(0, 1, (10, 10))
    m2 = np.random.normal(0, 1, (10, 10))
    vals[i] = np.max(m1.dot(m2))
    
print(np.average(vals))
print(np.percentile(vals, 95))

8.37191471375
11.9210444491


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [26]:
arr = np.random.poisson(5, 1000)
np.bincount(arr)

array([  6,  33,  85, 154, 161, 176, 161, 103,  50,  30,  24,  11,   3,
         2,   1])

#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [30]:
def super_repeat(a):
    arr_len = np.sum(a)
    arr = np.empty(arr_len, dtype=int)
    now = 0
    for i in range(len(a)):
        arr[now:now+a[i]] = np.repeat([i], a[i])
        now += a[i]
    return arr
super_repeat(np.array([1, 2, 3, 4, 0, 0, 0, 5], dtype=int))

array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 7, 7, 7, 7, 7])

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [46]:
def scale(X):
    eps = 0.0000001
    for i in range(X.shape[1]):
        e = np.average(X[:, i])
        d = np.std(X[:, i])
        if abs(d) > eps:
            X[:, i] -= e
            X[:, i] /= d
    return X
        
X = scale(np.array([[1, 2, 0], [1, 5, 0], [2, 8, 0]], dtype=float))
print(X)

[[-0.70710678 -1.22474487  0.        ]
 [-0.70710678  0.          0.        ]
 [ 1.41421356  1.22474487  0.        ]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [99]:
from numpy import linalg as la
m = np.random.normal(10, 1, (10, 10))
print(la.det(m))
print(np.trace(m))
print(np.min(m))
print(np.max(m))
print(la.norm(m))
print(la.norm(m, -2))
print(la.eig(m)[0])
print(la.inv(m))

224.681890924
104.86985068
7.56659779555
12.3511376474
100.918316805
0.00312542770902
[  1.00493935e+02+0.j          -2.05279076e+00+1.30872288j
  -2.05279076e+00-1.30872288j   3.06194221e+00+0.j           2.51906557e+00+0.j
   1.38891123e+00+1.60114872j   1.38891123e+00-1.60114872j
   5.85580477e-02+1.39913426j   5.85580477e-02-1.39913426j
   5.55120340e-03+0.j        ]
[[-17.14505614  -0.22699164 -29.86027578  26.31624296 -27.05303205
   11.08634933  30.36354696 -11.58860233  18.27223937   1.93115447]
 [  9.75036375   0.09591236  16.36199016 -14.83089575  14.94953946
   -6.01259019 -16.75222849   6.46730068  -9.88131052  -1.2682156 ]
 [ 26.517369     0.23224784  45.22493472 -39.66362688  40.57444965
  -16.5317826  -46.22570462  17.90829728 -27.93301325  -3.25842109]
 [-27.58812091  -0.48733643 -47.05450025  41.7024689  -42.63481059
   17.51347283  48.29200508 -18.51573847  29.02803173   3.05486055]
 [ 39.08416226   1.00642009  67.64212992 -59.74882271  61.2497904
  -25.05680785 -69.2

## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv("2008.csv", error_bad_lines=False)
data.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4     2003        1955     2211   
1  2008      1           3          4      754         735     1002   
2  2008      1           3          4      628         620      804   
3  2008      1           3          4      926         930     1054   
4  2008      1           3          4     1829        1755     1959   

   CRSArrTime UniqueCarrier  FlightNum        ...         TaxiIn  TaxiOut  \
0        2225            WN        335        ...              4        8   
1        1000            WN       3231        ...              5       10   
2         750            WN        448        ...              3       17   
3        1100            WN       1746        ...              3        7   
4        1925            WN       3920        ...              3       10   

   Cancelled  CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0          0               NaN         0           NaN          NaN      NaN   
1          0               NaN         0           NaN          NaN      NaN   
2          0               NaN         0           NaN          NaN      NaN   
3          0               NaN         0           NaN          NaN      NaN   
4          0               NaN         0             2            0        0   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4              0                 32  

[5 rows x 29 columns]

In [3]:
codes = data["CancellationCode"]
codes.value_counts() #B - weather

B    54904
A    54330
C    28188
D       12
dtype: int64

In [4]:
dists = data["Distance"]
print "Max: ", dists.max()
print "Average: ", dists.mean()
print "Min: ", dists.min()

Max:  4962
Average:  726.387029425
Min:  11


In [5]:
days = data[dists == dists.min()][["Year", "Month", "DayofMonth", "FlightNum", "UniqueCarrier"]].drop_duplicates()
print days
flights_nums = data[dists == dists.min()]["FlightNum"].drop_duplicates()
[data[data["FlightNum"] == flight_num]["Distance"].drop_duplicates().values for flight_num in flights_nums]

         Year  Month  DayofMonth  FlightNum UniqueCarrier
2547298  2008      5          15       4988            OH
4392215  2008      8          10       5572            OH


[array([834,  96,  11, 414, 223, 712, 321, 903]),
 array([544, 329,  11, 363, 134, 669, 508])]

In [7]:
airports = pd.read_csv("http://stat-computing.org/dataexpo/2009/airports.csv")

In [82]:
most_frequent_airport = data["Origin"].value_counts().index[0]
airports[airports["iata"] == most_frequent_airport]

iata                            airport     city state country        lat  \
880  ATL  William B Hartsfield-Atlanta Intl  Atlanta    GA     USA  33.640444   

          long  
880 -84.426944

In [8]:
origin_mean_airtime = data.groupby("Origin")["AirTime"].aggregate(np.mean)
print origin_mean_airtime.max()
airport_max = origin_mean_airtime.idxmax()
airports[airports["iata"] == airport_max]

203.850842697


iata                         airport      city state country        lat  \
2962  SJU  Luis Munoz Marin International  San Juan    PR     USA  18.439417   

           long  
2962 -66.001833

In [6]:
threshold = 1000
all_flights = data.groupby("Origin").size()
delayed_flights = data[data["DepDelay"] > 0].groupby("Origin").size()
fraction_delayed = delayed_flights[all_flights > threshold] / all_flights[all_flights > threshold]
max_fraction_delayed = fraction_delayed.idxmax()
print fraction_delayed.max()
airports[airports["iata"] == max_fraction_delayed]

0.578641892894


iata       airport    city state country        lat       long
1247  DAL  Dallas Love   Dallas    TX     USA  32.847114 -96.851772